import { Link } from 'react-router-dom';

const CHECKS = [
  'ACL and firewall rule gaps',
  'Flat networks and missing VLAN segmentation',
  'Insecure management protocols',
  'AAA, SSH/TLS, DNS, NTP, and logging coverage',
];

const STEPS = [
  { title: 'Upload topology JSON', text: 'Use the topology data generated by StructuraNet or any compatible network JSON.' },
  { title: 'Review security findings', text: 'See severity, affected categories, inventory details, and a clear security score.' },
  { title: 'Apply Cisco fixes', text: 'Open remediation commands for IOS hardening across routers, switches, and services.' },
];

function ShieldIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
      <path d="M9 12l2 2 4-4" />
    </svg>
  );
}

export default function SecurityFeature() {
  return (
    <section id="security-feature" className="relative overflow-hidden bg-[#020706] py-20 lg:py-28 border-y border-white/[0.08]">
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute left-1/2 top-0 h-[420px] w-[720px] -translate-x-1/2 rounded-full bg-emerald-500/10 blur-3xl" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_40%,rgba(16,185,129,0.12),transparent_28%),radial-gradient(circle_at_20%_75%,rgba(79,142,247,0.08),transparent_24%)]" />
      </div>

      <div className="relative mx-auto grid max-w-7xl gap-10 px-6 lg:grid-cols-[0.95fr_1.05fr] lg:items-center">
        <div>
          <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-emerald-300">
            <ShieldIcon />
            Security Feature
          </div>
          <h2 className="max-w-2xl text-3xl font-bold tracking-tight text-white sm:text-4xl lg:text-5xl">
            Check your generated topology before you deploy it
          </h2>
          <p className="mt-5 max-w-xl text-base leading-relaxed text-zinc-300">
            The Security Analyzer reads your topology JSON, scores the design, flags risky choices,
            and gives practical Cisco IOS remediation commands so you can harden the network with confidence.
          </p>

          <div className="mt-7 grid gap-3 sm:grid-cols-2">
            {CHECKS.map((item) => (
              <div key={item} className="flex items-start gap-3 text-sm text-zinc-300">
                <span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-emerald-400 shadow-[0_0_12px_rgba(52,211,153,0.8)]" />
                <span>{item}</span>
              </div>
            ))}
          </div>

          <div className="mt-8 flex flex-col gap-3 sm:flex-row">
            <Link to="/security" className="btn-primary justify-center">
              Open Security Analyzer
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M5 12h14M13 5l7 7-7 7" />
              </svg>
            </Link>
            <Link to="/register" className="btn-secondary justify-center">
              Create account
            </Link>
          </div>
        </div>

        <div className="rounded-2xl border border-white/[0.08] bg-zinc-950/80 p-4 shadow-2xl shadow-emerald-950/30">
          <div className="flex items-center justify-between border-b border-white/[0.08] pb-3">
            <div className="flex items-center gap-2 text-sm font-semibold text-white">
              <span className="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-400/12 text-emerald-300 ring-1 ring-emerald-400/25">
                <ShieldIcon />
              </span>
              Topology Security Report
            </div>
            <span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2.5 py-1 text-xs font-semibold text-emerald-300">
              Score 84/100
            </span>
          </div>

          <div className="mt-4 grid gap-3">
            {STEPS.map((step, index) => (
              <div key={step.title} className="rounded-xl border border-white/[0.07] bg-white/[0.03] p-4">
                <div className="mb-2 flex items-center gap-3">
                  <span className="inline-flex h-7 w-7 items-center justify-center rounded-lg bg-emerald-400/12 text-xs font-bold text-emerald-300 ring-1 ring-emerald-400/20">
                    {index + 1}
                  </span>
                  <h3 className="text-sm font-semibold text-white">{step.title}</h3>
                </div>
                <p className="text-sm leading-relaxed text-zinc-400">{step.text}</p>
              </div>
            ))}
          </div>

          <div className="mt-4 rounded-xl border border-orange-400/20 bg-orange-400/[0.06] p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-orange-300">Example finding</p>
            <p className="mt-2 text-sm text-zinc-300">
              No ACL / firewall rules found. Add deny-all defaults, then allow only required traffic between VLANs.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
